### ISSUE TITLE
Klassendiagramme

### ISSUE THREAD

**Issue by paulKlarer** [TimeLegend35/ATDIT2_Group_2#1]

**Comment by Tobux** [comment]
Erster Entwurf ohne Methoden aber sollte grundlegende Klassen für benötigte Funktionen abdecken


![Image](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/53224773/7605ce01-7f3a-4846-8bcd-75d926e7b43c)



[ATIT2_Group2_Schule_Klassendiagramm.zip](https://github.com/TimeLegend35/ATDIT2_Group_2/files/14808279/ATIT2_Group2_Schule_Klassendiagramm.zip)

**Comment by Tobux** [comment]
**Meeting Ergebnisse 02.04.2024**

Benachrichtigungen, historische Daten allgeimein fehlen @paulKlarer 
-> [Log Issue](https://github.com/users/TimeLegend35/projects/1/views/1?pane=issue&itemId=57905262)

Anwesenheitsabfrage für Lehrer fehlt in Klassendiag. und erd @paulKlarer @addisch04 

Error handling fehlt, brauchen wir
-> [Aktivitätsdiagramme issue](https://github.com/users/TimeLegend35/projects/1/views/1?pane=issue&itemId=57904412)

Krankmeldungssystem muss noch fertiggestellt werden

**Comment by Tobux** [comment]
![grafik](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/53224773/e00683a4-60b9-41f4-aa5a-84202afd3b71)
[ATIT2_Group2_Schule_Klassendiagramm.zip](https://github.com/TimeLegend35/ATDIT2_Group_2/files/14854493/ATIT2_Group2_Schule_Klassendiagramm.zip)

**Comment by Tobux** [comment]
Nach dem 1. Meeting finalisiertes Klassendiagramm.

![Image](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/53224773/29350929-41ca-447e-a813-52d5688c189f)



[ATIT2_Group2_Schule_Klassendiagramm_final.zip](https://github.com/TimeLegend35/ATDIT2_Group_2/files/14909231/ATIT2_Group2_Schule_Klassendiagramm_final.zip)
