### ISSUE TITLE
System für Rollen, Rechte, angepasste UIs & Funktionen

### ISSUE THREAD

**Issue by Tobux** [TimeLegend35/ATDIT2_Group_2#15]

**Comment by Tobux** [comment]
vielleicht nach einem cleaneren Weg schauen um das Session object als Rückgabe zu bekommen, idealerweise schon in der richtigen Klasse und nicht nur als User Object. Abfrage nach Typ der Rechte in UIs könnte vielleicht auch cleaner sein.

**Comment by paulKlarer** [comment]
wir über Session Instanz geregelt
