### ISSUE TITLE
Implementierung von Lokalisierung / Sprache

### ISSUE THREAD

**Issue by Tobux** [TimeLegend35/ATDIT2_Group_2#16]
Recherche Issue: [Link](https://github.com/users/TimeLegend35/projects/1/views/1?pane=issue&itemId=58414616)

**Comment by Tobux** [comment]
Implementierung von der benötigten UI: [Commit Link](https://github.com/TimeLegend35/ATDIT2_Group_2/commit/92fb08857d8cf1838266bfc7b9df32f1a8395edb)

**Comment by Tobux** [comment]
todo:

- [x] Login View Texte neu rendern wenn man die Sprache ändert

- [x] alle texte des programms in die properties dateien einfügen und Zugriff über LanguageHelper einfügen

**Comment by paulKlarer** [comment]
Für View Klassen außer Care Offer view

**Comment by Tobux** [comment]
Abgeschlossen für den jetzigen Stand. Für Errorhandling steht es jetzt auch im issue.
