### ISSUE TITLE
Model Builder

### ISSUE THREAD

**Issue by paulKlarer** [TimeLegend35/ATDIT2_Group_2#20]

**Comment by Tobux** [comment]
todo: fix care offer sql command and object creation in model builder and careoffermarketplace controller

**Comment by Tobux** [comment]
`private static CareOffer buildCareOffer(int careOfferId) { return null; }` mit Inhalt versorgen und in `buildServiceListForStudent(int studentId)` verwenden. Ebenso in noch nicht vorhandener Methode verwenden, die alle CareOffers erstellt und von CareOfferMarketplace gerufen werden kann, um die komplette CareOffer Liste zu ziehen. Dann wäre folgender Code nicht mehr redundant im ModelBuilder und CareOfferMarketplaceController:

```
List<Service> careOffers = new ArrayList<>();
        Service newCareOffer;

        for (Object[] row : results) {

            int id = (int) row[0];
            int supervisorId = (int) row[1];
            Supervisor supervisor = new Supervisor(supervisorId, "MasterSupervisor") ;
            int oldestClassLevel = (int) row[2];
            int youngestClassLevel = (int) row[3];
            String careOfferName = (String) row[4];
            String description = (String) row[5];
            int seatsAvailable = (int) row[6];

            newCareOffer = new CareOffer(id, supervisor, oldestClassLevel, youngestClassLevel, careOfferName, description, seatsAvailable);
            careOffers.add(newCareOffer);
        }

        return careOffers;
```

**Comment by Tobux** [comment]
ModelBuilder mit diesem [Issue ](https://github.com/users/TimeLegend35/projects/1/views/1?pane=issue&itemId=60717786)fürs erste abgeschlossen. Errorhandling kommt.
