### ISSUE TITLE
Junit Tests

### ISSUE THREAD

**Issue by paulKlarer** [TimeLegend35/ATDIT2_Group_2#21]

**Comment by samlra** [comment]
Wir sind uns unsicher bei Tests für:
Controller,
DialogHelper,
CareOfferMarketplaceView,
CareOfferView,
MainView,

**Comment by samlra** [comment]
Außerdem kann ich die Tests nicht ausführen. Ich bekomme diese Fehlermeldung: java: package io.github.cdimascio.dotenv does not exist

**Comment by paulKlarer** [comment]
Du hast beim einfügen der JUnit dependancy ausversehen 2 dependancies gelöscht. Eine davon war für den Import notwendig. Hab sie jetzt wieder eingefügt und gepushed. Bei mir laufen die Tests jetzt. Ich habe auch einen Test für noten Auskommentiert weil der hat Fehler geworfen und wir implementieren die Noten ja nicht deswegen brauchen wir es ja auch nicht Testen.

**Comment by paulKlarer** [comment]
Für die Fragen zu den einzelnen Tests wende dich an Tobi oder Lean. Bei den Views sollte Tobi bescheid wissen.

**Comment by paulKlarer** [comment]
Front_end und dao classen unit_tests

**Comment by samlra** [comment]
Tests für UI nach aktuellem stand soweit fertig, es fehlen:
DialogHelper, MainController und MainView.

Für CareOfferView + Controller und CareOfferMarketPlaceView + Controller habe ich Tests implementiert aber kriege die nicht zum laufen...

- [x] Tests Kommentieren
- [ ] Tests in Technische Doku übernehmen

**Comment by samlra** [comment]
Zu den model tests:
testAddStudentToStudentList aus dem ServiceTest läuft nicht korrekt, könnte das jemand double checken?

Bei den DAO Tests kriege ich immer einen ExceptionInInitializerError und weiß nicht woran das liegt.
