### ISSUE TITLE
Präsentation

### ISSUE THREAD

**Issue by paulKlarer** [TimeLegend35/ATDIT2_Group_2#26]

**Comment by paulKlarer** [comment]
1. https://slidesgo.com/theme/final-project-proposal#search-software+project&position-17&results-32&rs=search&rs=search 
2. https://slidesgo.com/theme/dark-elegant-korean-style-project-proposal#search-software+project&position-20&results-32&rs=search&rs=search
3. https://slidesgo.com/theme/business-proposition-canvas#search-software+project&position-32&results-32&rs=search

**Comment by samlra** [comment]
Ich finde die 3. am besten. Ich glaube wir können uns schon auf das Schul-Design einlassen und müssen es nicht zu professionell machen
Die hat eigentlich einen guten mix

**Comment by addisch04** [comment]
Bin auch für 3. Aus gleichen Gründen, wie Samira
