### ISSUE TITLE
DAO Logik für Speicherung

### ISSUE THREAD

**Issue by paulKlarer** [TimeLegend35/ATDIT2_Group_2#27]

**Comment by Tobux** [comment]
DBConnector braucht eine Methode wo kein Rückgabewert erwartet wird, ist gerade broken. @TimeLegend35 @paulKlarer 

Edit: done

**Comment by Tobux** [comment]
Todo: Anmeldungen werden nach logout nicht richtig gespeichert oder so, steht immer add am button.

**Comment by Tobux** [comment]
fix mit [diesem Issue](https://github.com/users/TimeLegend35/projects/1/views/1?pane=issue&itemId=60717786).

Speicherlogik ist implementiert.
