### ISSUE TITLE
Errorhandling & Logging

### ISSUE THREAD

**Issue by paulKlarer** [TimeLegend35/ATDIT2_Group_2#28]
Errorhandling für das gesamte Projekt

**Comment by Tobux** [comment]
Zum **Error Handling** und **Logging**: [Ideen / Möglichkeiten](https://chat.openai.com/share/d7a0f085-72af-4e23-b762-9c87aeed482e)
(Logging: Ich finde, dass `java.util.logging` (JUL) reicht, außerdem brauchen wir dann keine weiteren dependencies)

**Comment by Tobux** [comment]
+ todo: Fehlermeldungen und alles auch in jeweiliger Sprache verfügbar machen über `LanguageHelper`

**Comment by Tobux** [comment]
Vielleicht [das Issue](https://github.com/users/TimeLegend35/projects/1/views/1?pane=issue&itemId=60303029) im Errorhandling abschließen

**Comment by Tobux** [comment]
Done: First try to do it in DBConnector

**Comment by Tobux** [comment]
Done: Language System Error Handling and Logging like in the DBConnector
