### ISSUE TITLE
UI Mocks

### ISSUE THREAD

**Issue by paulKlarer** [TimeLegend35/ATDIT2_Group_2#3]

**Comment by samlra** [comment]
![Kopie von Screen-Prototype Eltern drawio](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/149785876/e1d60201-88ca-4a34-a7bf-933765ce293c)

**Comment by samlra** [comment]
![Kopie von Screen-prototype Kinder drawio](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/149785876/6853e0da-d409-4829-b7c3-f5a083812e0b)

**Comment by samlra** [comment]
![Kopie von Screen-prototypes Leher drawio](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/149785876/0ec01bff-3450-4fc4-bce9-59545283964e)

**Comment by paulKlarer** [comment]
Vielen Dank für die UI Mocks sieht grundsätzlich sehr gut aus.  
Ich bin mir nicht sicher ob ich das so mit der Startseite gut aussieht. Weil da ist sehr viel Platz für Events und ich weiß nicht ob wir genügend Demo Events haben, dass es gut aussieht. Vlt. hat man auf der Startseite einfach direkt seinen Kalender damit bei allen etwas angezeigt wird. 
Ich finde den Betreuungsmarktplatz beim UI für Eltern etwas verwirrend.
Die Funktionalität Kind anmelden müssen meines Verständnisses nach komplett ausgegliedert werden, weil Leute die ihr Kind anmelden sind nicht in Bad Waden registriert und haben dementsprechend keinen Bad Walden User. Ich glaube den Workflow, dass sie isch erst im Rathaus einen Badwalden user anlegen halte ich für unrealistisch.
Bei der Krankmeldung haben wir in der DB ein von bis vom Datum her und nicht von der Uhrzeit, dass können wir auch noch in die DB packen aber ich denke einen Möglichkeit sich für mehrere Tage Abwesend zu erklären sollte auch gegeben sein.
Fall ich was falsch verstanden hab gerne richtigstellen :)

**Comment by samlra** [comment]
@paulKlarer Danke für das Feedback.
Den Kalender als Startseite zu nehmen ist auch gut. Können wir gerne ändern. Aber den Menüpunkt würden wir trotzdem lassen, ist ja dann keine große Arbeit das anzupassen.
Der Betreuungsmarktplatz soll einfach so gegliedert sein, dass die Angebote alphabetisch sortiert aufgelistet sind und wenn man auf eins rauf drückt kommt man zu genaueren Infos dazu und zur anmeldung. Aus meiner Perspektive ergibt das Sinn, kannst du genauer erklären was verwirrend ist?
Müssen nicht alle Eltern ihr Kind anmelden nur die aus Bad Walden bekommen garantiert einen Platz?
Wir können aber auch auf dem Login Screen die Option hinzufügen für Aussenstehende ihre Kinder anzumelden, ohne Login. 
Und ich fande das mit der Uhrzeit bei den Krankmeldungen passend, falls man nur irgendwie eine stunde fehlt. Aber das Bis Datum ergänze ich!

**Comment by samlra** [comment]
Noch etwas zum Thema regestrierung: Hat einfach jeder mit Bad Walden ID zugriff auf das System, also auch wenn er gar kein Kind in der Schule hat? Oder muss es erst eine Option registrierung geben, oder melden alle eltern ihre Kinder ausgegliedert an?

**Comment by samlra** [comment]
![Kopie von Screen-Prototype Eltern drawio (1)](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/149785876/a448e8bd-9d60-432a-b7f0-76c20dda358b)
![Kopie von Screen-prototype Kinder drawio (1)](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/149785876/ea0322f5-6809-457d-92cc-38d9edc9c3a4)
![Kopie von Screen-prototypes Leher drawio (1)](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/149785876/14d41398-6ca2-4c0e-82c0-cd8d8f672351)

**Comment by paulKlarer** [comment]
> Noch etwas zum Thema regestrierung: Hat einfach jeder mit Bad Walden ID zugriff auf das System, also auch wenn er gar kein Kind in der Schule hat? Oder muss es erst eine Option registrierung geben, oder melden alle eltern ihre Kinder ausgegliedert an?

Es hat jeder aus Badwalden eine Badwalden-id. Die berechtigung wirden über rollen vergeben. Anmleden kann sich dann natürlich auch nur wer die entsprechende Rolle Erziehungsberchtigter, Schulkind oder Angestelter hat

**Comment by paulKlarer** [comment]
> [@paulKlarer](https://github.com/paulKlarer) Danke für das Feedback. Den Kalender als Startseite zu nehmen ist auch gut. Können wir gerne ändern. Aber den Menüpunkt würden wir trotzdem lassen, ist ja dann keine große Arbeit das anzupassen. Der Betreuungsmarktplatz soll einfach so gegliedert sein, dass die Angebote alphabetisch sortiert aufgelistet sind und wenn man auf eins rauf drückt kommt man zu genaueren Infos dazu und zur anmeldung. Aus meiner Perspektive ergibt das Sinn, kannst du genauer erklären was verwirrend ist? Müssen nicht alle Eltern ihr Kind anmelden nur die aus Bad Walden bekommen garantiert einen Platz? Wir können aber auch auf dem Login Screen die Option hinzufügen für Aussenstehende ihre Kinder anzumelden, ohne Login. Und ich fande das mit der Uhrzeit bei den Krankmeldungen passend, falls man nur irgendwie eine stunde fehlt. Aber das Bis Datum ergänze ich!

Danke für die Erklärung zum Betreungsmarktplatz. Dann hatte ich da die UI Mocks nicht verstanden. Den von dir beschriebenen Ablauf finde ich gut.

Also so wie ich es vertsehe bekommen Kinder aus Badwalden automatisch einen Platz. Ich hätte gesagt sie müssten sich expliziert abmelden wenn sie woanders auf die Schule wollen. Dementsprechend glaube ich ist die Anmeldung nur für außenstehende relevant. Finde die Idee das beim ans login anzugleidern gut. Dann müssen wir dort alle Infos von den Kindern und ihren Eltern erfassen

Ja das mit Uhrzeit in der Krankmeldung finde ich sehr gut

**Comment by samlra** [comment]
![Externe Anmeldung Screen-Prototype drawio](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/149785876/295b892d-8d57-48dd-bbfc-ee2a2a27332b)

**Comment by samlra** [comment]
![Überarbeitung Screen-prototype Kinder drawio](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/149785876/fb49f5bd-75ed-4093-bfdf-660f58a4ea5e)
![Überarbeitet Screen-Prototype Eltern drawio (1)](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/149785876/9fcdd846-f287-4b9b-87a6-c6aaf640f099)
![Überarbeitung Screen-prototypes Leher drawio](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/149785876/7fac111d-91a7-452f-b7f4-98cf213b4dfb)
