### ISSUE TITLE
ERD überarbeiten

### ISSUE THREAD

**Issue by paulKlarer** [TimeLegend35/ATDIT2_Group_2#33]

**Comment by addisch04** [comment]
@paulKlarer können uns gerne zusammensetzen, falls du hilfe brauchst.

**Comment by paulKlarer** [comment]
> [@paulKlarer](https://github.com/paulKlarer) können uns gerne zusammensetzen, falls du hilfe brauchst.

Gerne

**Comment by paulKlarer** [comment]
https://miro.com/welcomeonboard/a1luNkc5MVZSVTNTOEN0U05qa2NHVDVTWndHZVBYb3VPZ3dNbFZobDRKU0JNMWtiTkdkc1lMTlFBd3p5dUpEV3wzNDU4NzY0NTY1NzcxNDMzNzY5fDI=?share_link_id=328876482350
