### ISSUE TITLE
Aktivitätsdiagramm überarbeiten

### ISSUE THREAD

**Issue by paulKlarer** [TimeLegend35/ATDIT2_Group_2#35]

**Comment by samlra** [comment]
![Image](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/149785876/b8603e47-ad43-4899-86cf-a54b3b60b146)
![Image](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/149785876/8ec171cb-4c0e-49d1-8e8b-476f87729ca8)

**Comment by paulKlarer** [comment]
sieht echt super aus. Gerne dann auch direkt in die PowerPoint
