### ISSUE TITLE
Aktivitätsdiagramme

### ISSUE THREAD

**Issue by Tobux** [TimeLegend35/ATDIT2_Group_2#4]

**Comment by samlra** [comment]
![Kopie von Aktivitätsdiagramm Leher drawio](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/149785876/ff446a23-fae7-4629-971f-d37b6f28e810)
Ich habe nur für einen Ausgewählten Prozess ein Aktivitätsdiagramm gemacht. Wenn man alle Optionen im System berücksichtigt, wird das Diagramm viel zu voll

**Comment by NajaPiaLehmann** [comment]
![AktivitätsdiagrammEltern drawio](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/149786910/58077bbb-d988-44da-a103-90c68cc13cd5)

**Comment by samlra** [comment]
Hier meine Überarbeitung des Diagramms für einen Use-Case von Lehrern
![Überarbeitung Aktivitätsdiagramm Leher drawio](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/149785876/6b1d2a25-8993-46d5-b9a9-2401b9876c9e)

**Comment by NajaPiaLehmann** [comment]
Hier noch einer exemplarischer Prozess für den Zugriff der Kinder:
![AktivitätsdiagrammKinder drawio](https://github.com/TimeLegend35/ATDIT2_Group_2/assets/149786910/eb0975a7-f319-4bc6-8f9f-ab5f8a10ee96)
