### ISSUE TITLE
Datenbankshema in Central Board bringen

### ISSUE THREAD

**Issue by paulKlarer** [TimeLegend35/ATDIT2_Group_2#7]
Hier ist das zentrale Datenbank übersicht: https://excalidraw.com/#room=a7a748a44f5d51241496,G6Npw_nP8uEk57barYeQNQ

Meeting Zusammenfassung:

- 3 Gruppen eine Datenbank: Schwimmbad Gruppe muss sich noch überlegen.
- Gemeinsame Badwalden Nutzer: Rathaus übernimmt Nutzer Erstellung und Verwaltung wir müssen uns einfach nur fürs einloggen bei uns kümmern.
- Gemiensame Tabelle mit Rollen und user rollenzuweisung. 3 Universale rollen sonst beliebig viele gruppenspezifische User
- Kein Gemeinsames UI / Navigationsübersicht

**Comment by paulKlarer** [comment]
Schwimmbad Gruppe nutzt eigene DB

**Comment by paulKlarer** [comment]
@addisch04 @Tobux @TimeLegend35 @samlra @NajaPiaLehmann hatte gerade nochmal ein meeting mit der Rathaus- und Stadtwerke gruppe. 
1. Wir können externe in der Einwohnertabelle anlegen um nicht BadWaldener abzubilden. Diese bekommen dann die Rolle externen zugewiesen und haben nur Zugriff auf unsere Anwendung.
2. Man könne zwar Mutter und Vater in der Geburtentabelle angeben aber das ist statisch und wird nicht im laufe des Lebens verändert werden und bildet somit nicht alle Lebensrealitäten ab.  Der Vorschlag war da dass wir die beiden Erziehungsberechtigten als Fremdschlüssel beim Kind speichern. Gerne darüber nachdenken wie das unsre Prozesse beeinflusst und ob das Akzeptabel ist. Lass morgen nochmal darüber abstimmen. Dann kann ich auch alles nochmal genauer erläutern. Bis morgen

**Comment by addisch04** [comment]
> @addisch04 @Tobux @TimeLegend35 @samlra @NajaPiaLehmann hatte gerade nochmal ein meeting mit der Rathaus- und Stadtwerke gruppe.
> 
>     1. Wir können externe in der Einwohnertabelle anlegen um nicht BadWaldener abzubilden. Diese bekommen dann die Rolle externen zugewiesen und haben nur Zugriff auf unsere Anwendung.
> 
>     2. Man könne zwar Mutter und Vater in der Geburtentabelle angeben aber das ist statisch und wird nicht im laufe des Lebens verändert werden und bildet somit nicht alle Lebensrealitäten ab.  Der Vorschlag war da dass wir die beiden Erziehungsberechtigten als Fremdschlüssel beim Kind speichern. Gerne darüber nachdenken wie das unsre Prozesse beeinflusst und ob das Akzeptabel ist. Lass morgen nochmal darüber abstimmen. Dann kann ich auch alles nochmal genauer erläutern. Bis morgen

Also ich sehe kein Problem damit, wenn man die Eltern als Fremdschlüssel beim Kind speichert. An sich finde ich die Option: "Erziehungsberechtigten ändern" sowieso etwas zu detailiert/kompliziert. Finde es somit sogar fast besser die Eltern als "statische" Objekte zu speichern :)

**Comment by paulKlarer** [comment]
Ich denke schon dass es möglich sein sollte die Erziehungsberechtigten zu ändern. Einfach um alle Familiensituationen abbilden zukönnen

**Comment by paulKlarer** [comment]
Haben uns gerade auf das finale DB Schema geeinigt das wir am Freitag vorstellen. ;)
