### ISSUE TITLE
Reviews mit Britta und Patrick

### ISSUE THREAD

**Issue by paulKlarer** [TimeLegend35/ATDIT2_Group_2#8]
Unser Thema: Schule
Was wir liefern müssen:
 
Git mit Readme’s
Design und Entwurfsdokumente für die Komplette Lösung
Prozess und Datenbank Modellierung (Entity Relationship Diagram)
UI überlegung was brauchen die für UI. Wer bekommt was zu sehen. (User; Power-User(personas); Admins)
Anwendungssoftware (Kernprozesse und Main-Features für MVP) Modellierung
 
**Ziel: alles im GitHub zur Verfügung stellen und in der Besprechung wird entschieden was man aus programmiert werden soll**

Schreibt gerne noch Punkte die ihr im Meeting besprechen wollt dazu und unsere Meeting Notizen können wir auch hier machen-

**Comment by paulKlarer** [comment]
- Full integration mit Rathaus DB? Frage wegen der ziehen der Erziehungsberechtigte aus den entsprechenden Tabellen.
- nur ein prozess, Krankmeldung, Kind-Anmelden und Notengebung von Britta angesprochen
- sequenz dieagram für das ausprogramierrte der rest prozess oder aktivitätsdiagramme. usecase diagramm.
- nicht in Klassen sondern in Schnittstellen/Interfaces zu denken
- Solid Prinzip beim programieren beachten

**Comment by samlra** [comment]
- Kind für Betreuungsangebot anmelden wäre guter Prozess zum umsetzen

**Comment by paulKlarer** [comment]
**2.Meeting**
Mehr in Schnittstellendenken. 
DAO Objecte als Schnittstelle abgebildet
Abhängigkeiten Dependancy injection
Abschluss präsentation: 25 min. Die ganze Idee wird vorgestellt.
Frühzeitg an Technische Docu denken und auch an UnitTests.
Montag 22 mögliches Code Review mit Patrick.
Alles was nicht perfekt ist an Coding löschen
Login Screen passt schon. 
entweder Lehrer oder Eltern view ausprogrammiert reicht

**Comment by Tobux** [comment]
Keine Reviews mehr.
